version: "3"

services:
  db:
    image: mysql:latest
    container_name: "PythonMySQLDB"
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: s3cr37
      MYSQL_USER: pythonuser
      MYSQL_PASSWORD: s3cr37
      MYSQL_DATABASE: PythonDB